/* version.c */

/*
 * Copyright (c) 1997-2010, 2012-2014 Wind River Systems, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/types.h>
#include "version.h" /* generated by MAKE, at compile time */

#ifdef CONFIG_VERSION_HEADER
#include <kernel_version.h>
/* The content of this struct is overwritten in a post-build script */
struct version_header version_header __attribute__((section(".version_header")))
__attribute__((used)) = {
	.magic = {'$', 'B', '!', 'N'},
	.version = KERNELVERSION,
};
#endif

/**
 *
 * @brief Return the kernel version of the present build
 *
 * The kernel version is a four-byte value, whose format is described in the
 * file "kernel_version.h".
 *
 * @return kernel version
 */
u32_t sys_kernel_version_get(void)
{
	return KERNELVERSION;
}
